## Data

In [1]:
import pandas as pd

In [5]:
# wikipedia

wiki = pd.read_csv('../data/wikipedia_data.csv')

In [25]:
timeseries = wiki.loc[wiki['date'] == '6/01/2016']

In [41]:

timeseries.groupby(by = ['language', 'access', 'agent']).count()

                           project  article  granularity  date  views  Purpose
language access    agent
de       desktop   spider       38       38           38    38     38       38
                   user         38       38           38    38     38       38
         mobileapp user         30       30           30    30     30       30
         mobileweb spider       24       24           24    24     24       24
                   user         38       38           38    38     38       38
en       desktop   spider       93       93           93    93     93       93
                   user         93       93           93    93     93       93
         mobileapp user         74       74           74    74     74       74
         mobileweb spider       92       92           92    92     92       92
                   user         93       93           93    93     93       93
es       desktop   spider       38       38           38    38     38       38
                   user         38       38           38    38     38       38
         mobileapp user         25       25           25    25     25       25
         mobileweb spider       31       31           31    31     31       31
                   user         38       38           38    38     38       38
zh       desktop   spider       29       29           29    29     29       29
                   user         29       29           29    29     29       29
         mobileapp user         14       14           14    14     14       14
         mobileweb spider       29       29           29    29     29       29
                   user         29       29           29    29     29       29

In [5]:
labour = pd.read_csv('../data/labour_processed.csv')

In [11]:
main_occu = labour.loc[labour['Main_occupation'] == 'Community and Personal Service Workers']
main_occu.loc[main_occu['Sub_occupation'] == 'Community and Personal Service Workers nfd']

,Sex,Month,Sub_occupation,Employment_status,Count,Main_occupation
20668,Males,2008 May,Community and Personal Service Workers nfd,Full time,0.000000,Community and Personal Service Workers
20669,Males,2008 May,Community and Personal Service Workers nfd,Part time,0.097662,Community and Personal Service Workers

"1986 Aug","1986 Nov",
"1987 Feb","1987 May","1987 Aug","1987 Nov",
"1988 Feb","1988 May","1988 Aug","1988 Nov",
"1989 Feb","1989 May","1989 Aug","1989 Nov",
"1990 Feb","1990 May","1990 Aug","1990 Nov",
"1991 Feb","1991 May","1991 Aug","1991 Nov",
"1992 Feb","1992 May","1992 Aug","1992 Nov",
"1993 Feb","1993 May","1993 Aug","1993 Nov",
"1994 Feb","1994 May","1994 Aug","1994 Nov",
"1995 Feb","1995 May","1995 Aug","1995 Nov",
"1996 Feb","1996 May","1996 Aug","1996 Nov",
"1997 Feb","1997 May","1997 Aug","1997 Nov",
"1998 Feb","1998 May","1998 Aug","1998 Nov",
"1999 Feb","1999 May","1999 Aug","1999 Nov",
"2000 Feb","2000 May","2000 Aug","2000 Nov",
"2001 Feb","2001 May","2001 Aug","2001 Nov",
"2002 Feb","2002 May","2002 Aug","2002 Nov",
"2003 Feb","2003 May","2003 Aug","2003 Nov",
"2004 Feb","2004 May","2004 Aug","2004 Nov",
"2005 Feb","2005 May","2005 Aug","2005 Nov",
"2006 Feb","2006 May","2006 Aug","2006 Nov",
"2007 Feb","2007 May","2007 Aug","2007 Nov",
"2008 Feb","2008 May","2008 Aug","2008 Nov",
"2009 Feb","2009 May","2009 Aug","2009 Nov",
"2010 Feb","2010 May","2010 Aug","2010 Nov",
"2011 Feb","2011 May","2011 Aug","2011 Nov",
"2012 Feb","2012 May","2012 Aug","2012 Nov",
"2013 Feb","2013 May","2013 Aug","2013 Nov",
"2014 Feb","2014 May","2014 Aug","2014 Nov",
"2015 Feb","2015 May","2015 Aug","2015 Nov",
"2016 Feb","2016 May","2016 Aug","2016 Nov",
"2017 Feb","2017 May","2017 Aug","2017 Nov",
"2018 Feb","2018 May"